language: android

install:
  # Download SDK
  - yes | sdkmanager "tools" &>/dev/null
  - yes | sdkmanager "platform-tools" &>/dev/null
  - yes | sdkmanager "platforms;android-29" &>/dev/null
  # Update remaining dependencies and accept licenses
  - yes | sdkmanager --update &>/dev/null
  - yes | sdkmanager --licenses &>/dev/null

android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.0
    - android-28
    - extra-android-m2repository

jdk:
  - oraclejdk8

notifications:
  email: false

script:
  - chmod +x gradlew
  - ./gradlew assemble check
#  - ./gradlew checkstyle

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
